### ISSUE TITLE
Druckkopf lässt sich nicht flashen

### ISSUE THREAD

**Issue by RicardoHipp** [leadustin/QIDI-up2date-german#3]
Hallo

wenn ich den Befehl

sudo mount /dev/sda1 /mnt

eingebe, mountet er zwar, aber nur read only.

Ich habe das Gefühl das das drücken des Bootknopf keine Auswirkung hat.
Habe alle möglichen Konstellationen  der beiden Knöpfe durchprobiert.

Ich habe allerdings auch die Platinen Version 1-4V1.2 an meinem X-Max 3 , muss man da anders vorgehen?

**Comment by leadustin** [comment]
Hallo, 

hast du den kompletten Befehl in die Konsole übertragen?
sudo mount /dev/sda1 /mnt
systemctl daemon-reload

**Comment by leadustin** [comment]
Da es keine weiteren Fragen zu geben scheint. Close

**Comment by leadustin** [comment]
Da es keine weiteren Fragen zu geben scheint.
